import elevation from './private/elevation.css';
export const elevationSurfaceSunkenBg = elevation.elevationSurfaceSunkenBg;
export const elevationSurfaceBg = elevation.elevationSurfaceBg;
export const elevationSurfaceRaisedBg = elevation.elevationSurfaceRaisedBg;
export const elevationSurfaceFloatingBg = elevation.elevationSurfaceFloatingBg;
export const elevationSurfaceRestingShadow = elevation.elevationSurfaceRestingShadow;
export const elevationSurfaceRaisedShadow = elevation.elevationSurfaceRaisedShadow;
export const elevationSurfaceFloatingShadow = elevation.elevationSurfaceFloatingShadow;
export const elevationActionRaised = elevation.elevationActionRaised;
export const elevationActionResting = elevation.elevationActionResting;
