/**
 * @public
 * A disclosure identifying if the app generated this asset using AI.
 *
 * @remarks
 * Helps users make informed decisions about the content they interact with.
 *
 * AI is generally defined as any machine system that, given an objective, infers how to generate an output from an input.
 * Some examples include "generative AI", "large language models", and "machine learning".
 *
 * **App Generated**
 *
 * 'app_generated' indicates when the app creates or significantly alters an asset using AI. Includes when
 * the app makes a request to a third-party service to do so.
 *
 * A significantly altered asset means the AI changes key information or details, such as
 * removing or replacing key components in the original content, which can include applying style transfer, or changing facial expressions.
 *
 * Label this asset as 'app_generated' under these conditions:
 *
 * The following is true:
 *
 * - The app generates the asset in response to a user's request (including past requests), for example, the asset is not from an asset library.
 *
 * And any of these conditions are also true:
 *
 *  - The AI creates entirely new content from scratch.
 *  - The AI introduces new multimedia, details, or creative elements not originally present.
 *  - The AI removes and replaces the asset's key components.
 *  - The AI alters the asset's appearance, meaning, or context in a way that conveys a different message than the original.
 *
 * **None**
 *
 * 'none' indicates when the asset wasn't generated by the app as a part of any user's specific request, for example, a third-party
 * request, or when the asset wasn't significantly altered by AI.
 */
declare type AiDisclosure = 'app_generated' | 'none';

declare type AllOrNone<T> = T | Never<T>;

/**
 * @public
 * {@link GetDataTableError} indicating custom error occurred in the app's implementation.
 * This can be used to indicate specific issues that are not covered by other error types.
 */
declare type AppError = {
    /**
     * A custom error occurred in your app.
     *
     * Return this for application-specific errors that don't fit
     * the other categories. Include a descriptive message explaining
     * the error to the user.
     */
    status: 'app_error';
    /**
     * Optional message explaining the error.
     */
    message?: string;
};

/**
 * @public
 * {@link PublishContentError} indicating a custom error occurred in your app's implementation.
 *
 * Return this for application-specific errors such as:
 *
 * - Validation failures
 * - Authentication errors
 * - Rate limiting
 * - Platform-specific restrictions
 *
 * @example Returning custom error with message
 * ```ts
 * if (userQuotaExceeded) {
 *   return {
 *     status: 'app_error',
 *     message: 'You have reached your monthly publish limit. Please upgrade your plan.'
 *   };
 * }
 * ```
 */
declare type AppError_2 = {
    status: 'app_error';
    /**
     * (required) The raw error message, for logging purposes. It will not display in the UI.
     * To display custom error messages in the UI use `localizedMessageId`.
     *
     * This should typically be the javascript error.message or a REST JSON error message
     * body passed without modification.
     *
     * WARNING: Do not include personally identifiable information (PII) in this
     * message, such as names, emails, usernames, etc.
     */
    message: string;
    /**
     * (optional) Message ID of the translated error message that will be
     * displayed to the user. The message ID should be present and uploaded in
     * your translation file. If omitted, Canva will display a generic error
     * message.
     */
    localizedMessageId?: string;
    /** HTTP status code, if applicable */
    httpCode?: number;
    /**
     * Used only by app developer. Canva does not use this value. Use this to pass
     * additional information like JSON to your settings frame.
     */
    appDefinedPayload?: string;
    /**
     * (optional) Source of the error if it relates to a component on the Canva
     * UI. When present, the error may render near a relevant Canva component.
     * When omitted, the cause is considered unspecified or "generic".
     */
    errorCause?: ErrorCause;
};

/**
 * @public
 * {@link InvocationContext} indicating a custom error occurred during data refresh.
 * Triggered when getDataTable returned 'app_error' status.
 * UI should display the error message and help users recover.
 */
declare type AppErrorInvocationContext = {
    /**
     * A custom error occurred during data refresh.
     *
     * This occurs when `getDataTable` returned 'app_error' during a refresh attempt.
     * Your UI should display the error message and help users recover from the specific
     * issue.
     */
    reason: 'app_error';
    /**
     * The data source reference that caused the error during refresh.
     */
    dataSourceRef?: DataSourceRef;
    /**
     * The error message to display to the user.
     */
    message?: string;
};

/**
 * @public
 * Base file requirement interface.
 */
declare interface BaseFileRequirement {
    /**
     * File format for this requirement.
     */
    format: PublishFileFormat;

}

/**
 * @public
 * Base interface for exported files.
 */
declare interface BaseOutputFile {
    /**
     * File format.
     */
    format: PublishFileFormat;
    /**
     * URL to download the exported file.
     *
     * Your app should download from this URL and upload to your platform.
     */
    url: string;
    /**
     * Metadata about the source content used to create this exported file.
     */
    contentMetadata: ContentMetadata;
}

/**
 * @public
 * Base interface for all preview types.
 *
 * Contains common properties shared by all preview types.
 */
declare interface BasePreview {
    /**
     * Unique identifier for this preview.
     *
     * Use this ID with `requestPreviewUpgrade` to upgrade thumbnails to full previews.
     */
    id: string;
    /**
     * Type of media in this preview.
     */
    kind: PreviewKind;
    /**
     * Current state of the preview.
     */
    status: PreviewStatus;
}

/**
 * @public
 * Base metadata available for a selected media item in a media slot.
 *
 * Canva populates this when returning {@link OutputType} in Settings UI contexts.
 * Apps should not set this value.
 */
declare interface BaseSelection {
    /**
     * Metadata about the source content represented by this selection.
     */
    selectionMetadata?: readonly SelectionMetadata[];
}

/**
 * @public
 * Cell containing a boolean value.
 *
 * @example Creating a boolean cell
 * ```ts
 * import type { BooleanDataTableCell } from '@canva/intents/data';
 *
 * const isActiveCell: BooleanDataTableCell = {
 *   type: 'boolean',
 *   value: true
 * };
 * ```
 *
 * @example Creating a boolean cell with false value
 * ```ts
 * import type { BooleanDataTableCell } from '@canva/intents/data';
 *
 * const isCompleteCell: BooleanDataTableCell = {
 *   type: 'boolean',
 *   value: false
 * };
 * ```
 *
 * @example Creating an empty boolean cell
 * ```ts
 * import type { BooleanDataTableCell } from '@canva/intents/data';
 *
 * const emptyBooleanCell: BooleanDataTableCell = {
 *   type: 'boolean',
 *   value: undefined
 * };
 * ```
 */
declare type BooleanDataTableCell = {
    /**
     * Indicates this cell contains a boolean value.
     */
    type: 'boolean';
    /**
     * Boolean value (true or false).
     *
     * Use `undefined` for an empty cell.
     */
    value: boolean | undefined;
};

/**
 * @public
 * Configuration for a table column.
 */
declare type ColumnConfig = {
    /**
     * Name for the column, displayed as header text.
     *
     * If `undefined`, the column will have no header text.
     */
    name: string | undefined;
    /**
     * Expected data type for cells in this column.
     *
     * Use a specific `DataType` for columns with consistent types,
     * or `'variant'` for columns that may contain mixed types.
     */
    type: DataType | 'variant';
};

declare namespace content {
    export {
        prepareContentPublisher,
        Disposer,
        PublishContentRequest,
        RenderSettingsUiInvocationContext,
        PublishSettingsUiInvocationContext,
        RenderSettingsUiRequest,
        OnContextChange,
        SettingsUiContext,
        PublishSettingsSettingsUiContext,
        PublishErrorSettingsUiContext,
        PublishErrorClearedSettingsUiContext,
        PublishError,
        PublishSettings,
        PublishRefValidityState,
        UpdatePublishSettingsResponse,
        UpdatePublishSettingsCompleted,
        PublishContentResponse,
        PublishContentCompleted,
        PostPublishAction,
        PostPublishActionRedirect,
        PublishContentError,
        RemoteRequestFailedError_2 as RemoteRequestFailedError,
        AppError_2 as AppError,
        ErrorCause,
        GetPublishConfigurationResponse,
        GetPublishConfigurationCompleted,
        GetPublishConfigurationError,
        OutputType,
        OutputTypeConfiguration,
        MediaSlot,
        ImageRequirement,
        VideoRequirement,
        DocumentRequirement,
        EmailRequirement,
        BaseSelection,
        MediaSelection,
        ImageSelection,
        VideoSelection,
        DocumentSelection,
        EmailSelection,
        SelectionMetadata,
        SelectionDesignMetadata,
        DocumentSize,
        PublishFileFormat,
        ExactValueRange,
        MinValueRange,
        MaxValueRange,
        MinMaxValueRange,
        ValueRange,
        DocumentPreview,
        DocumentPreviewLoading,
        DocumentPreviewThumbnail,
        DocumentPreviewUpgrading,
        DocumentPreviewReady,
        DocumentPreviewPage,
        DocumentPreviewError,
        ImagePreview,
        ImagePreviewLoading,
        ImagePreviewReady,
        ImagePreviewError,
        VideoPreview,
        VideoPreviewLoading,
        VideoPreviewThumbnail,
        VideoPreviewUpgrading,
        VideoPreviewReady,
        VideoPreviewError,
        EmailPreview,
        EmailPreviewLoading,
        EmailPreviewReady,
        EmailPreviewError,
        BasePreview,
        SizedPreview,
        PreviewKind,
        PreviewStatus,
        OutputMedia,
        OutputFile,
        ImageOutputFile,
        VideoOutputFile,
        BaseOutputFile,
        DocumentOutputFile,
        EmailOutputFile,
        ContentMetadata,
        DesignContentMetadata,
        OutputPageMetadata,
        Preview,
        PreviewMedia,
        RenderPreviewUiInvocationContext,
        PublishPreviewUiInvocationContext,
        RenderPreviewUiRequest,
        ContentPublisherIntent
    }
}
export { content }

/**
 * @public
 * Metadata about the source content used to create an exported file.
 */
declare type ContentMetadata = DesignContentMetadata;

/**
 * @public
 * Main interface for implementing the ContentPublisher intent.
 *
 * Implementing the ContentPublisher intent enables apps to publish contents to external platforms.
 * This allows users to configure publish settings, preview their designs, and share with others.
 *
 * The publishing flow follows this process:
 *
 * 1. User initiates publish action
 * 2. Your app provides publish configuration via `getPublishConfiguration`
 * 3. User selects an output type
 * 4. Your app renders settings UI via `renderSettingsUi`
 * 5. Your app renders preview UI via `renderPreviewUi`
 * 6. User reviews settings and preview
 * 7. Your app publishes the content via `publishContent`
 */
declare type ContentPublisherIntent = {
    /**
     * Provides the configuration for the publishing platform.
     *
     * This action is called when the user initiates the publish flow and needs to
     * select an output type for the target platform.
     *
     * Use this to define different publishing configurations for your platform,
     * such as social media posts, videos, or other output types.
     *
     * @returns A promise resolving to the publish configuration or an error
     *
     * @example Defining publish configuration for a social media platform
     * ```ts
     * import type { GetPublishConfigurationResponse } from '@canva/intents/content';
     *
     * async function getPublishConfiguration(): Promise<GetPublishConfigurationResponse> {
     *   return {
     *     status: 'completed',
     *     outputTypes: [
     *       {
     *         id: 'instagram_post',
     *         displayName: 'Instagram Post',
     *         mediaSlots: [
     *           {
     *             id: 'main_image',
     *             displayName: 'Post Image',
     *             fileCount: { min: 1, max: 10 },
     *             accepts: {
     *               image: { format: 'jpg', aspectRatio: { min: 0.8, max: 1.91 } }
     *             }
     *           }
     *         ]
     *       }
     *     ]
     *   };
     * }
     * ```
     */
    getPublishConfiguration: () => Promise<GetPublishConfigurationResponse>;

    /**
     * Renders a user interface for configuring publish settings.
     *
     * This action is called after the user selects an output type. Your UI should
     * allow users to configure platform-specific settings such as captions, tags,
     * privacy settings, or publishing destinations.
     *
     * Use the `updatePublishSettings` callback to save user settings and validate them.
     * Settings are stored in the `publishRef` string (maximum 32KB).
     *
     * @param request - Configuration and callbacks for the publish settings UI.
     *
     * @example Rendering a settings UI with publish configuration
     * ```ts
     * import { createRoot } from 'react-dom/client';
     * import type { RenderSettingsUiRequest } from '@canva/intents/content';
     *
     * function renderSettingsUi(request: RenderSettingsUiRequest): void {
     *   const SettingsUiApp = () => (
     *      <AppUiProvider>
     *       <SettingsUi request={request} />
     *     </AppUiProvider>
     *   );
     *
     *   createRoot().render(<SettingsUiApp />)
     * }
     * ```
     */
    renderSettingsUi: (request: RenderSettingsUiRequest) => void;
    /**
     * Renders a user interface for previewing the content.
     *
     * This action is called after the settings UI is rendered. Your UI should display
     * a preview of how the content will appear on the target platform.
     *
     * Previews update dynamically as users modify their content or settings. For videos,
     * start with lightweight thumbnails and use `requestPreviewUpgrade` to load full
     * video previews on demand to optimize performance.
     *
     * @param request - Configuration and callbacks for the preview UI.
     *
     * @example Rendering a preview UI with video optimization
     * ```ts
     * import { createRoot } from 'react-dom/client';
     * import type { RenderPreviewUiRequest } from '@canva/intents/content';
     *
     * function renderPreviewUi(request: RenderPreviewUiRequest): void {
     *   const PreviewUiApp = () => (
     *      <AppUiProvider>
     *       <PreviewUi request={request} />
     *     </AppUiProvider>
     *   );
     *
     *   createRoot().render(<PreviewUiApp />)
     * }
     * ```
     */
    renderPreviewUi: (request: RenderPreviewUiRequest) => void;
    /**
     * Publishes the content to the external platform.
     *
     * This action is called when the user confirms the publish action after reviewing
     * settings and preview. Your implementation should send the exported files
     * to your platform's API.
     *
     * The `outputMedia` contains production-ready files that match the requirements
     * specified in your output types. The `publishRef` contains the user's settings
     * from the settings UI.
     *
     * @param request - Parameters for the publish operation.
     * @returns A promise resolving to either a successful result with the published content details or an error.
     *
     * @example Publishing content to an external platform
     * ```ts
     * import type { PublishContentRequest, PublishContentResponse } from '@canva/intents/content';
     *
     * async function publishContent(request: PublishContentRequest): Promise<PublishContentResponse> {
     *   const { publishRef, outputType, outputMedia } = request;
     *
     *   try {
     *     // Parse settings from publishRef
     *     const settings = publishRef ? JSON.parse(publishRef) : {};
     *
     *     // Upload files to your platform
     *     const uploadedFiles = await Promise.all(
     *       outputMedia.flatMap(media =>
     *         media.files.map(file => uploadFile(file.url))
     *       )
     *     );
     *
     *     // Create post on your platform
     *     const result = await createPost({
     *       files: uploadedFiles,
     *       caption: settings.caption
     *     });
     *
     *     return {
     *       status: 'completed',
     *       externalId: result.id,
     *       externalUrl: result.url
     *     };
     *   } catch (error) {
     *     return {
     *       status: 'remote_request_failed'
     *     };
     *   }
     * }
     * ```
     */
    publishContent: (request: PublishContentRequest) => Promise<PublishContentResponse>;


};

declare namespace data {
    export {
        prepareDataConnector,
        DataConnectorIntent,
        GetDataTableRequest,
        RenderSelectionUiRequest,
        InvocationContext,
        GetDataTableResponse,
        GetDataTableCompleted,
        DataTableMetadata,
        GetDataTableError,
        UpdateDataRefResponse,
        DataSourceRef,
        DataTableLimit,
        DataType,
        DataTable,
        ColumnConfig,
        DataTableRow,
        DataTableCell,
        DateDataTableCell,
        StringDataTableCell,
        NumberDataTableCell,
        NumberCellMetadata,
        BooleanDataTableCell,
        MediaCollectionDataTableCell,
        DataTableImageUpload,
        DataTableVideoUpload
    }
}
export { data }

/**
 * @public
 * Main interface for implementing the Data Connector intent.
 *
 * Implementing the Data Connector intent enables apps to import external data into Canva.
 * This allows users to select, preview, and refresh data from external sources.
 */
declare type DataConnectorIntent = {
    /**
     * Gets structured data from an external source.
     *
     * This action is called in two scenarios:
     *
     * - During data selection to preview data before import (when {@link RenderSelectionUiRequest.updateDataRef} is called).
     * - When refreshing previously imported data (when the user requests an update).
     *
     * @param request - Parameters for the data fetching operation.
     * @returns A promise resolving to either a successful result with data or an error.
     *
     * @example Getting data from an external source
     * ```ts
     * import type { GetDataTableRequest, GetDataTableResponse } from '@canva/intents/data';
     *
     * async function getDataTable(request: GetDataTableRequest): Promise<GetDataTableResponse> {
     *   const { dataSourceRef, limit, signal } = request;
     *
     *   // Check if the operation has been aborted.
     *   if (signal.aborted) {
     *     return { status: 'app_error', message: 'The data fetch operation was cancelled.' };
     *   }
     *
     *   // ... data fetching logic using dataSourceRef, limit, and signal ...
     *
     *   // Placeholder for a successful result.
     *   return {
     *     status: 'completed',
     *     dataTable: { rows: [{ cells: [{ type: 'string', value: 'Fetched data' }] }] }
     *   };
     * }
     * ```
     */
    getDataTable: (request: GetDataTableRequest) => Promise<GetDataTableResponse>;

    /**
     * Renders a user interface for selecting and configuring data from your external sources.
     *
     * @param request - Configuration and callbacks for the data selection UI.
     *
     * @example Rendering a data selection UI
     * ```ts
     * import type { RenderSelectionUiRequest } from '@canva/intents/data';
     *
     * async function renderSelectionUi(request: RenderSelectionUiRequest): Promise<void> {
     *   // UI rendering logic.
     *   // Example: if user selects data 'ref123'.
     *   const selectedRef = { source: 'ref123', title: 'My Selected Table' };
     *   try {
     *     const result = await request.updateDataRef(selectedRef);
     *     if (result.status === 'completed') {
     *       console.log('Selection valid and preview updated.');
     *     } else {
     *       console.error('Selection error:', result.status);
     *     }
     *   } catch (error) {
     *      console.error('An unexpected error occurred during data ref update:', error);
     *   }
     * }
     * ```
     */
    renderSelectionUi: (request: RenderSelectionUiRequest) => void;
};

/**
 * @public
 * {@link InvocationContext} indicating initial data selection flow or edit of existing data.
 */
declare type DataSelectionInvocationContext = {
    /**
     * Initial data selection or editing existing data.
     *
     * This is the standard flow when:
     *
     * - A user is selecting data for the first time
     * - A user is editing a previous selection
     *
     * If `dataSourceRef` is provided, this indicates an edit flow, and you should
     * pre-populate your UI with this selection.
     */
    reason: 'data_selection';
    /**
     * If dataSourceRef is provided, this is an edit of existing data flow and UI should be pre-populated.
     */
    dataSourceRef?: DataSourceRef;
};

/**
 * @public
 * Reference to an external data source that can be used to fetch data.
 * Created by Data Connector apps and stored by Canva for data refresh operations.
 *
 * You create this object in your data selection UI and pass it to the
 * `updateDataRef` callback. Canva stores this reference and uses it for
 * future data refresh operations.
 *
 * Maximum size: 5KB
 *
 * @example Defining how to locate external data
 * ```ts
 * const dataSourceRef: DataSourceRef = {
 *   source: JSON.stringify({
 *     reportId: "monthly_sales_001",
 *     filters: { year: 2023, region: "NA" }
 *   }),
 *   title: "Monthly Sales Report (NA, 2023)"
 * };
 * ```
 */
declare type DataSourceRef = {
    /**
     * Information needed to identify and retrieve data from your source.
     *
     * This string should contain all the information your app needs to
     * fetch the exact data selection later. Typically, this is a serialized
     * object with query parameters, identifiers, or filters.
     *
     * You are responsible for encoding and decoding this value appropriately.
     *
     * Maximum size: 5KB
     */
    source: string;
    /**
     * A human-readable description of the data reference.
     *
     * This title may be displayed to users in the Canva interface to help
     * them identify the data source.
     *
     * Maximum length: 255 characters
     */
    title?: string;
};

/**
 * @public
 * Structured tabular data for import into Canva.
 *
 * This format allows you to provide typed data with proper formatting
 * to ensure it displays correctly in Canva designs.
 *
 * @example Creating a data table
 * ```ts
 * import type { ColumnConfig, DataTableCell, DataTable, DataTableRow } from '@canva/intents/data';
 *
 * const myTable: DataTable = {
 *   columnConfigs: [
 *     { name: 'Name', type: 'string' },
 *     { name: 'Age', type: 'number' },
 *     { name: 'Subscribed', type: 'boolean' },
 *     { name: 'Join Date', type: 'date' }
 *   ],
 *   rows: [
 *     {
 *       cells: [
 *         { type: 'string', value: 'Alice' },
 *         { type: 'number', value: 30 },
 *         { type: 'boolean', value: true },
 *         { type: 'date', value: Math.floor(new Date('2023-01-15').getTime() / 1000) }
 *       ]
 *     },
 *     {
 *       cells: [
 *         { type: 'string', value: 'Bob' },
 *         { type: 'number', value: 24 },
 *         { type: 'boolean', value: false },
 *         { type: 'date', value: Math.floor(new Date('2022-07-20').getTime() / 1000) }
 *       ]
 *     }
 *   ]
 * };
 * ```
 */
declare type DataTable = {
    /**
     * Column definitions with names and data types.
     *
     * These help Canva interpret and display your data correctly.
     */
    columnConfigs?: ColumnConfig[];
    /**
     * The data rows containing the actual values.
     *
     * Each row contains an array of cells with typed data values.
     */
    rows: DataTableRow[];
};

/**
 * @public
 * Generic type for table cells that resolves to a specific cell type.
 */
declare type DataTableCell<T extends DataType = DataType> = {
    date: DateDataTableCell;
    string: StringDataTableCell;
    number: NumberDataTableCell;
    boolean: BooleanDataTableCell;
    media: MediaCollectionDataTableCell;
}[T];

/**
 * @public
 * Options for uploading an image asset to the user's private media library.
 */
declare type DataTableImageUpload = Omit<ImageUploadOptions, 'type' | 'parentRef'> & {
    /**
     * Indicates this value contains options for image uploading.
     */
    type: 'image_upload';
};

/**
 * @public
 * Maximum dimensions for imported data tables.
 */
declare type DataTableLimit = {
    /**
     * The maximum number of rows allowed.
     *
     * Your app should ensure data does not exceed this limit.
     */
    row: number;
    /**
     * The maximum number of columns allowed.
     *
     * Your app should ensure data does not exceed this limit.
     */
    column: number;
};

/**
 * @public
 * Metadata providing additional context about the imported data.
 */
declare type DataTableMetadata = {
    /**
     * A human-readable description of the dataset.
     *
     * This description helps users understand what data they are importing.
     */
    description?: string;
    /**
     * Information about the data provider or source.
     */
    providerInfo?: {
        /**
         * Name of the data provider.
         */
        name: string;
        /**
         * URL to the provider's website or related resource.
         */
        url?: string;
    };
};

/**
 * @public
 * A row in the data table.
 *
 * @example Creating a single row of data cells
 * ```ts
 * import type { DataTableCell, DataTableRow } from '@canva/intents/data';
 *
 * const row: DataTableRow = {
 *   cells: [
 *     { type: 'string', value: 'Product Alpha' },
 *     { type: 'number', value: 199.99 },
 *     { type: 'boolean', value: true }
 *   ]
 * };
 * ```
 */
declare type DataTableRow = {
    /**
     * Array of cells containing the data values.
     *
     * Each cell must have a type that matches the corresponding column definition (if provided).
     */
    cells: DataTableCell<DataType>[];
};

/**
 * @public
 * Options for uploading a video asset to the user's private media library.
 */
declare type DataTableVideoUpload = Omit<VideoUploadOptions, 'type' | 'parentRef'> & {
    /**
     * Indicates this value contains options for video uploading.
     */
    type: 'video_upload';
};

/**
 * @public
 * Data types supported for table cells.
 */
declare type DataType = 'string' | 'number' | 'date' | 'boolean' | 'media';

/**
 * @public
 * Cell containing a date value.
 *
 * @example Creating a date cell
 * ```ts
 * import type { DateDataTableCell } from '@canva/intents/data';
 *
 * const todayCell: DateDataTableCell = {
 *   type: 'date',
 *   value: Math.floor(Date.now() / 1000) // Unix timestamp in seconds
 * };
 *
 * const emptyDateCell: DateDataTableCell = {
 *   type: 'date',
 *   value: undefined
 * };
 * ```
 */
declare type DateDataTableCell = {
    /**
     * Indicates this cell contains a date value.
     */
    type: 'date';
    /**
     * Unix timestamp in seconds representing the date.
     *
     * Use `undefined` for an empty cell.
     */
    value: number | undefined;
};

declare namespace design {
    export {
        prepareDesignEditor,
        DesignEditorIntent
    }
}
export { design }

/**
 * @public
 * Metadata specific to design content.
 */
declare interface DesignContentMetadata {
    type: 'design';
    /**
     * A signed JWT token containing the design id
     */
    designToken: string;
    /**
     * The user given title of the design
     */
    title: string | undefined;
    /**
     * The pages that make up the exported metadata
     */
    pages: OutputPageMetadata[];

}

/**
 * @public
 *
 * Main interface for implementing the DesignEditor intent.
 *
 * Implementing the DesignEditor Intent enables apps to assist users in editing designs,
 * by presenting interactive and creative tooling alongside the Canva design surface.
 */
declare type DesignEditorIntent = {
    /**
     * Renders the UI containing the app’s functionality.
     *
     * @example
     * ```tsx
     * function render() {
     *   // render your UI using your preferred framework
     * }
     * ```
     */
    render: () => void;
};

/**
 * @public
 * A set of dimensions.
 */
declare type Dimensions = {
    /**
     * A width, in pixels.
     */
    width: number;
    /**
     * A height, in pixels.
     */
    height: number;
};

/**
 * @public
 * A function that can be called to dispose of a callback.
 */
declare type Disposer = () => void;

/**
 * @public
 * Exported PDF file ready for publishing.
 *
 * Contains the final PDF document that should be uploaded to your platform.
 * The document format is `pdf_standard` and the file is ready to use.
 */
declare type DocumentOutputFile = BaseOutputFile;

/**
 * @public
 * Document preview in various states.
 *
 * Documents transition through states: `"loading"` → `"thumbnail"` → `"upgrading"` → `"ready"`.
 * Start with a lightweight thumbnail of the first page, then upgrade to full multi-page
 * preview using `requestPreviewUpgrade`.
 */
declare type DocumentPreview = DocumentPreviewLoading | DocumentPreviewThumbnail | DocumentPreviewUpgrading | DocumentPreviewReady | DocumentPreviewError;

/**
 * @public
 * Document preview that failed to generate.
 *
 * Display an error state to the user.
 */
declare interface DocumentPreviewError extends SizedPreview {
    kind: 'document';
    status: 'error';
    /**
     * The error message to display to the user.
     */
    message: string;
}

/**
 * @public
 * Document preview that is currently being generated.
 *
 * Display a loading state until the preview transitions to `"thumbnail"` or `"error"`.
 */
declare interface DocumentPreviewLoading extends SizedPreview {
    kind: 'document';
    status: 'loading';
}

/**
 * @public
 * Thumbnail for a single page within a document preview.
 */
declare interface DocumentPreviewPage {
    /**
     * URL to the page thumbnail image.
     */
    url: string;
    /**
     * Width of the page thumbnail in pixels.
     */
    widthPx: number;
    /**
     * Height of the page thumbnail in pixels.
     */
    heightPx: number;
}

/**
 * @public
 * Final state after a document preview has been upgraded. Contains thumbnail
 * URLs for every selected page in the document.
 */
declare interface DocumentPreviewReady extends BasePreview {
    kind: 'document';
    status: 'ready';
    /**
     * Format of the per-page thumbnails.
     */
    format: 'png' | 'jpg';
    /**
     * Thumbnail pages for each page. Index corresponds to the page number.
     */
    pages: DocumentPreviewPage[];
}

/**
 * @public
 * Document preview with first page thumbnail available.
 *
 * This is the initial state for document previews. Show the thumbnail image
 * of the first page to give users a quick preview of the document.
 * Call `requestPreviewUpgrade` to load all page thumbnails.
 */
declare interface DocumentPreviewThumbnail extends SizedPreview {
    kind: 'document';
    status: 'thumbnail';
    /**
     * Format of the thumbnail image.
     */
    thumbnailFormat: 'png' | 'jpg';
    /**
     * URL to the first page thumbnail.
     *
     * Display this lightweight image to preview the document content.
     */
    thumbnailUrl: string;
}

/**
 * @public
 * Intermediate state while multi-page document thumbnails are being fetched
 * via {@link requestPreviewUpgrade}. The single-page thumbnail remains
 * available for display during the upgrade.
 */
declare interface DocumentPreviewUpgrading extends SizedPreview {
    kind: 'document';
    status: 'upgrading';
    /**
     * Format of the thumbnail image.
     */
    thumbnailFormat: 'png' | 'jpg';
    /**
     * URL to the first page thumbnail.
     *
     * Continue showing this while the upgrade loads.
     */
    thumbnailUrl: string;
}

/**
 * @public
 * Document file requirements for a media slot.
 *
 * Note: Document output types use image previews (PNG thumbnails) in the preview UI.
 * The actual document file is only generated for the final output in OutputMedia.
 *
 * @example Document requirements
 * ```ts
 * const documentReq: DocumentRequirement = {
 *   format: 'pdf_standard',
 *   size: 'a4',
 * };
 * ```
 */
declare interface DocumentRequirement extends BaseFileRequirement {
    /**
     * Supported document export format.
     * Currently supports PDF standard format.
     */
    format: 'pdf_standard';
    /**
     * The document size of the export file.
     */
    size: DocumentSize;
}

/**
 * @public
 * Selection metadata for a document media item.
 */
declare interface DocumentSelection extends BaseSelection {
    kind: 'document';
}

/**
 * @public
 * Document size for document exports.
 */
declare type DocumentSize = 'a4' | 'a3' | 'letter' | 'legal';

/**
 * @public
 * Exported email file ready for publishing.
 *
 * Contains the final HTML bundle that should be uploaded to your platform.
 */
declare type EmailOutputFile = BaseOutputFile;

/**
 * @public
 * Email preview in various states.
 *
 * Display a loading state until the preview transitions to `"ready"` or `"error"`.
 */
declare type EmailPreview = EmailPreviewLoading | EmailPreviewReady | EmailPreviewError;

/**
 * @public
 * Email preview in an error state.
 *
 * Display an error state to the user.
 */
declare interface EmailPreviewError extends BasePreview {
    kind: 'email';
    status: 'error';
    message: string;
}

/**
 * @public
 * Email preview in a loading state.
 *
 * Display a loading spinner until the preview transitions to `"ready"` or `"error"`.
 */
declare interface EmailPreviewLoading extends BasePreview {
    kind: 'email';
    status: 'loading';
}

/**
 * @public
 * Email preview in a ready state.
 *
 * Display the email preview.
 */
declare interface EmailPreviewReady extends BasePreview {
    kind: 'email';
    status: 'ready';
    /**
     * URL to the single html file that represents the email.
     */
    url: string;
}

/**
 * @public
 * Email file requirements for a media slot, currently only supports HTML bundle format.
 *
 * Note: Email output types use html_standalone previews in the preview UI.
 * The actual email file is only generated for the final output in OutputMedia.
 *
 * @example Email bundle requirements
 * ```ts
 * const emailReq: EmailRequirement = {
 *   format: 'html_bundle',
 * };
 * ```
 */
declare interface EmailRequirement extends BaseFileRequirement {
    format: 'html_bundle' | 'html_standalone';
}

/**
 * @public
 * Selection metadata for an email media item.
 */
declare interface EmailSelection extends BaseSelection {
    kind: 'email';
}

/**
 * @public
 *
 * The cause of an error
 */
declare type ErrorCause = 'invalid_selection' | 'invalid_format';

/**
 * @public
 * Exact value range constraint.
 * @example Exact value range
 * ```ts
 * const exactValue: ValueRange = { exact: 1 }; // Must be exactly 1
 * ```
 */
declare type ExactValueRange = {
    exact: number;
};

/**
 * @public
 * Successful result from `getDataTable` action.
 */
declare type GetDataTableCompleted = {
    /**
     * Indicates the operation completed successfully
     */
    status: 'completed';
    /**
     * The fetched data formatted as a data table.
     */
    dataTable: DataTable;
    /**
     * Optional metadata providing additional context about the data.
     */
    metadata?: DataTableMetadata;
};

/**
 * @public
 * Error results that can be returned from `getDataTable` method.
 */
declare type GetDataTableError = OutdatedSourceRefError | RemoteRequestFailedError | AppError;

/**
 * @public
 * Parameters for the getDataTable action.
 */
declare type GetDataTableRequest = {
    /**
     * Reference to the data source to fetch.
     *
     * This contains the information needed to identify and retrieve the specific data
     * that was previously selected by the user.
     *
     * Use this to query your external data service.
     */
    dataSourceRef: DataSourceRef;
    /**
     * Maximum row and column limits for the imported data.
     *
     * Your app must ensure the returned data does not exceed these limits.
     *
     * If the requested data would exceed these limits, either:
     *
     * - Truncate the data to fit within limits, or
     * - Return a 'data_table_limit_exceeded' error
     */
    limit: DataTableLimit;
    /**
     * Standard DOM AbortSignal for cancellation support.
     *
     * Your app should monitor this signal and abort any ongoing operations if it becomes aborted.
     */
    signal: AbortSignal;
};

/**
 * @public
 * Result returned from the `getDataTable` action.
 */
declare type GetDataTableResponse = GetDataTableCompleted | GetDataTableError;

/**
 * @public
 * Successful response from getting publish configuration.
 */
declare type GetPublishConfigurationCompleted = {
    status: 'completed';
    /**
     * Array of available output types for your platform.
     *
     * Define different output types for various content formats that
     * your platform supports (e.g., posts, stories, videos).
     */
    outputTypes: OutputTypeConfiguration[];
};

/**
 * @public
 * {@link GetPublishConfigurationError} error indicating a custom error occurred.
 */
declare type GetPublishConfigurationError = AppError_2;

/**
 * @public
 * Response from getting publish configuration.
 */
declare type GetPublishConfigurationResponse = GetPublishConfigurationCompleted | GetPublishConfigurationError;

/**
 * @public
 * The MIME type of an image file that's supported by Canva's backend.
 */
declare type ImageMimeType = 'image/jpeg' | 'image/heic' | 'image/png' | 'image/svg+xml' | 'image/webp' | 'image/tiff';

/**
 * @public
 * Exported image file ready for publishing.
 */
declare interface ImageOutputFile extends BaseOutputFile {
    /**
     * Width of the image in pixels.
     */
    widthPx: number;
    /**
     * Height of the image in pixels.
     */
    heightPx: number;
}

/**
 * @public
 * Image preview in various states.
 */
declare type ImagePreview = ImagePreviewLoading | ImagePreviewReady | ImagePreviewError;

/**
 * @public
 * Image preview that failed to generate.
 *
 * Display an error state to the user.
 */
declare interface ImagePreviewError extends SizedPreview {
    kind: 'image';
    status: 'error';

    /**
     * The error message to display to the user.
     */
    message: string;
}

/**
 * @public
 * Image preview that is currently being generated.
 *
 * Display a loading state until the preview transitions to `"ready"` or `"error"`.
 */
declare interface ImagePreviewLoading extends SizedPreview {
    kind: 'image';
    status: 'loading';
}

/**
 * @public
 * Image preview that is ready to display.
 *
 * Contains the URL to the preview image.
 */
declare interface ImagePreviewReady extends SizedPreview {
    kind: 'image';
    status: 'ready';
    /**
     * Image format of the preview.
     */
    format: 'png' | 'jpg';
    /**
     * URL to the preview image.
     *
     * Use this URL to display the preview to users.
     */
    url: string;
}

/**
 * @public
 * A unique identifier that points to an image asset in Canva's backend.
 */
declare type ImageRef = string & {
    __imageRef: never;
};

/**
 * @public
 * Image file requirements for a media slot.
 *
 * Specifies format, aspect ratio, and size constraints for images.
 *
 * @example Image requirements for social media post
 * ```ts
 * const imageReq: ImageRequirement = {
 *   format: 'jpg',
 *   aspectRatio: { min: 0.8, max: 1.91 },
 * };
 * ```
 */
declare type ImageRequirement = BaseFileRequirement & {
    /**
     * Aspect ratio constraint (width / height).
     *
     * Examples:
     * - `{ exact: 16/9 }`: Widescreen (16:9)
     * - `{ min: 0.8, max: 1.91 }`: Instagram range
     */
    aspectRatio?: ValueRange;
} & ({
    /**
     * JPG image export.
     */
    format: 'jpg';
} | {
    /**
     * PNG image export.
     */
    format: 'png';
    /**
     * Controls transparent-background support for PNG exports.
     *
     * @remarks
     * - Only applies when `format` is `'png'`
     * - If omitted or `false`, Canva exports a standard opaque PNG
     * - If `true`, Canva shows a `Transparent background` toggle in the publish flow
     * - Users without the required Canva entitlement may be prompted to upgrade before a transparent export is produced
     *
     * @defaultValue false
     */
    allowTransparentBackground?: boolean;
});

/**
 * @public
 * Selection metadata for an image media item.
 */
declare interface ImageSelection extends BaseSelection {
    kind: 'image';
}

/**
 * @public
 * Options for uploading an image asset to the user's private media library.
 */
declare type ImageUploadOptions = {
    /**
     * The type of asset.
     */
    type: 'image';
    /**
     * A human-readable name for the image asset.
     *
     * @remarks
     * This name is displayed in the user's media library and helps users identify
     * and find the asset later. If not provided, Canva will generate a name based
     * on the asset's URL or a unique identifier.
     *
     * Requirements:
     * - Minimum length: 1 character (empty strings are not allowed)
     * - Maximum length: 255 characters
     */
    name?: string;
    /**
     * The ref of the original asset from which this new asset was derived.
     *
     * @remarks
     * For example, if an app applies an effect to an image, `parentRef` should contain the ref of the original image.
     */
    parentRef?: ImageRef;
    /**
     * The URL of the image file to upload.
     * This can be an external URL or a data URL.
     *
     * @remarks
     * Requirements for external URLs:
     *
     * - Must use HTTPS
     * - Must return a `200` status code
     * - `Content-Type` must match the file's MIME type
     * - Must be publicly accessible (i.e. not a localhost URL)
     * - Must not redirect
     * - Must not contain an IP address
     * - Maximum length: 4096 characters
     * - Must not contain whitespace
     * - Must not contain these characters: `>`, `<`, `{`, `}`, `^`, backticks
     * - Maximum file size: 50MB
     *
     * Requirements for data URLs:
     *
     * - Must include `;base64` for base64-encoded data
     * - Maximum size: 10MB (10 × 1024 × 1024 characters)
     *
     * Requirements for SVGs:
     *
     * - Disallowed elements:
     *    - `a`
     *    - `altglyph`
     *    - `altglyphdef`
     *    - `altglyphitem`
     *    - `animate`
     *    - `animatemotion`
     *    - `animatetransform`
     *    - `cursor`
     *    - `discard`
     *    - `font`
     *    - `font-face`
     *    - `font-face-format`
     *    - `font-face-name`
     *    - `font-face-src`
     *    - `font-face-uri`
     *    - `foreignobject`
     *    - `glyph`
     *    - `glyphref`
     *    - `missing-glyph`
     *    - `mpath`
     *    - `script`
     *    - `set`
     *    - `switch`
     *    - `tref`
     * - Disallowed attributes:
     *    - `crossorigin`
     *    - `lang`
     *    - `media`
     *    - `onload`
     *    - `ping`
     *    - `referrerpolicy`
     *    - `rel`
     *    - `rendering-intent`
     *    - `requiredextensions`
     *    - `requiredfeatures`
     *    - `systemlanguage`
     *    - `tabindex`
     *    - `transform-origin`
     *    - `unicode`
     *    - `vector-effect`
     * - The `href` attribute of an `image` element only supports data URLs for PNG and JPEG images.
     * - The URL in the `href` attribute must not point to a location outside of the SVG.
     * - The `style` attribute must not use the `mix-blend-mode` property.
     */
    url: string;
    /**
     * The MIME type of the image file.
     */
    mimeType: ImageMimeType;
    /**
     * The URL of a thumbnail image to display while the image is queued for upload.
     * This can be an external URL or a data URL.
     *
     * @remarks
     * Requirements for external URLs:
     *
     * - Must use HTTPS
     * - Must support [Cross-Origin Resource Sharing](https://www.canva.dev/docs/apps/cross-origin-resource-sharing/)
     * - Must be a PNG, JPEG, or SVG file
     * - Maximum length: 4096 characters
     *
     * Requirements for data URLs:
     *
     * - Must include `;base64` for base64-encoded data
     * - Maximum size: 10MB (10 × 1024 × 1024 characters)
     */
    thumbnailUrl: string;
    /**
     * A disclosure identifying if the app generated this image using AI
     *
     * @remarks
     * Helps users make informed decisions about the content they interact with.
     * See {@link AiDisclosure} for the full definition.
     *
     * **App Generated**
     *
     * 'app_generated' indicates when the app creates or significantly alters an asset using AI. Includes when
     * the app requests a third-party service to take similar action on an image using AI.
     *
     *  Required for the following cases (this list is not exhaustive):
     *  | Case                                                            | Reason                               |
     *  | --                                                              | --                                   |
     *  | AI generates a new image from scratch                           | Creates new creative content         |
     *  | AI changes the style of the image e.g. makes it cartoon         | Significantly alters the style       |
     *  | AI removes an object and replaces it with new content           | Creates new creative content         |
     *  | AI changes the facial expression of a person in an image        | Can alter content's original meaning |
     *  | AI composites multiple images together                          | Significantly alters context         |
     *  | AI expands an image by generating new content to fill the edges | Creates new creative content         |
     *  | AI replaces background by generating new content                | Creates new creative content         |
     *
     * **None**
     *
     * 'none' indicates when the app doesn't create or significantly alter an asset using AI, or as a part of a request
     * to third-party hosted content.
     *
     * Required for the following cases (this list is not exhaustive):
     *  | Case                                                    | Reason                                    |
     *  | --                                                      | --                                        |
     *  | Asset comes from an asset library                       | Didn't generate the asset itself          |
     *  | AI corrects red eyes                                    | A minor correction                        |
     *  | AI removes background without replacement               | Doesn't change original meaning by itself |
     *  | AI changes the color of an object in an image           | Doesn't change original meaning by itself |
     *  | AI detects image defects and suggests manual fixes      | Didn't change the asset itself            |
     *  | AI adjusts brightness and contrast on an image          | Doesn't change original meaning by itself |
     *  | AI upscales an image                                    | Doesn't change original meaning by itself |
     */
    aiDisclosure: AiDisclosure;

} & AllOrNone<Dimensions>;

/**
 * @public
 * Information explaining why the data selection UI was launched.
 */
declare type InvocationContext = DataSelectionInvocationContext | OutdatedSourceRefInvocationContext | AppErrorInvocationContext;

/**
 * @public
 * Maximum value range constraint.
 * @example Maximum value range
 * ```ts
 * const maxValue: ValueRange = { max: 10 }; // At most 10
 * ```
 */
declare type MaxValueRange = {
    max: number;
};

/**
 * @public
 * Cell containing a media collection (images) value.
 *
 * @example Creating a media cell with an image
 * ```ts
 * import type { MediaCollectionDataTableCell } from '@canva/intents/data';
 *
 * const mediaCell: MediaCollectionDataTableCell = {
 *   type: 'media',
 *   value: [{
 *     type: 'image_upload',
 *     url: 'https://www.canva.dev/example-assets/image-import/image.jpg',
 *     mimeType: 'image/jpeg',
 *     thumbnailUrl: 'https://www.canva.dev/example-assets/image-import/thumbnail.jpg',
 *     aiDisclosure: 'none'
 *   }]
 * };
 * ```
 *
 * @example Creating an empty media cell
 * ```ts
 * import type { MediaCollectionDataTableCell } from '@canva/intents/data';
 *
 * const emptyMediaCell: MediaCollectionDataTableCell = {
 *   type: 'media',
 *   value: []
 * };
 * ```
 */
declare type MediaCollectionDataTableCell = {
    /**
     * Indicates this cell contains a media collection.
     */
    type: 'media';
    /**
     * Media collection values.
     *
     * Use empty array for an empty cell.
     */
    value: (DataTableImageUpload | DataTableVideoUpload)[];
};

/**
 * @public
 * Metadata about a selected media item in a media slot.
 */
declare type MediaSelection = ImageSelection | VideoSelection | DocumentSelection | EmailSelection;

/**
 * @public
 * Configuration for a media slot within an output type.
 *
 * Defines what type of media is accepted, requirements, and constraints.
 *
 * @example Image slot with aspect ratio requirements
 * ```ts
 * const thumbnailSlot: MediaSlot = {
 *   id: 'thumbnail',
 *   displayName: 'Video Thumbnail',
 *   fileCount: { exact: 1 },
 *   accepts: {
 *     image: {
 *       format: 'jpg',
 *       aspectRatio: { exact: 16/9 },
 *     }
 *   }
 * };
 * ```
 */
declare type MediaSlot = {
    /**
     * Unique identifier for this media slot within the output type.
     */
    id: string;
    /**
     * User-facing name for this media slot.
     *
     * Examples: `"Post Image"`, `"Video Thumbnail"`, `"Main Video"`.
     */
    displayName: string;
    /**
     * Number of files accepted in this slot.
     *
     * Use this to specify single or multiple file requirements.
     * Examples:
     * - `{ exact: 1 }`: Exactly one file
     * - `{ min: 1, max: 10 }`: Between 1 and 10 files
     * - undefined: Any number of files
     */
    fileCount?: ValueRange;
    /**
     * File type requirements for this slot.
     *
     * Note the following behavior:
     *
     * - Provide at least one of `image` or `video`
     * - If both are provided, files for this slot may be either images or videos; each file
     *   must satisfy the corresponding requirement for its media type
     * - To restrict the slot to a single media type, provide only that requirement
     * - `fileCount` applies across all files accepted by the slot regardless of media type
     * - Document output types will show image previews (PNG thumbnail) in preview UI
     */
    accepts: {
        image?: ImageRequirement;
        video?: VideoRequirement;
        document?: DocumentRequirement;
        /**
         * Email output types will show a single html file (canva hosted assets) preview in preview UI
         */
        email?: EmailRequirement;
    };
    /**
     * @public
     * Current selection for this slot.
     *
     * Canva populates this only when returning {@link OutputType} in Settings UI contexts
     * such as {@link RenderSettingsUiInvocationContext} and {@link PublishSettingsSettingsUiContext}.
     * Apps should not set this value when defining output types in
     * {@link ContentPublisherIntent.getPublishConfiguration}.
     */
    readonly selection?: readonly MediaSelection[];
};

/**
 * @public
 * Minimum and maximum value range constraint.
 * Ranges are inclusive `(min ≤ value ≤ max)`.
 * @example Minimum and maximum value range
 * ```ts
 * const minMaxValue: ValueRange = { min: 1, max: 10 }; // Between 1 and 10
 * ```
 */
declare type MinMaxValueRange = {
    min: number;
    max: number;
};

/**
 * @public
 * Minimum value range constraint.
 * @example Minimum value range
 * ```ts
 * const minValue: ValueRange = { min: 3 }; // At least 3
 * ```
 */
declare type MinValueRange = {
    min: number;
};

declare type Never<T> = {
    [key in keyof T]?: never;
};

/**
 * @public
 * Formatting metadata for number cells.
 *
 * @example Formatting as currency
 * ```ts
 * import type { NumberDataTableCell } from '@canva/intents/data';
 *
 * const currencyCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 1234.57,
 *   metadata: { formatting: '[$$]#,##0.00' }
 * };
 * ```
 *
 * @example Formatting as a percentage
 * ```ts
 * import type { NumberDataTableCell } from '@canva/intents/data';
 *
 * const percentCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 0.1234,
 *   metadata: { formatting: '0.00%' }
 * };
 * ```
 *
 * @example Applying a thousands separator
 * ```ts
 * import type { NumberDataTableCell } from '@canva/intents/data';
 *
 * const largeNumberCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 1234567.89234,
 *   metadata: { formatting: '#,##0.00' }
 * };
 * ```
 */
declare type NumberCellMetadata = {
    /**
     * Formatting pattern using Office Open XML Format.
     *
     * These patterns control how numbers are displayed to users,
     * including currency symbols, decimal places, and separators.
     */
    formatting?: string;
};

/**
 * @public
 * Cell containing a numeric value.
 *
 * @example Creating a number cell
 * ```ts
 * import type { NumberCellMetadata, NumberDataTableCell } from '@canva/intents/data';
 *
 * const priceCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 29.99,
 *   metadata: { formatting: '[$$]#,##0.00' }
 * };
 *
 * const quantityCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: 150
 * };
 *
 * const emptyNumberCell: NumberDataTableCell = {
 *   type: 'number',
 *   value: undefined
 * };
 * ```
 */
declare type NumberDataTableCell = {
    /**
     * Indicates this cell contains a number value.
     */
    type: 'number';
    /**
     * Numeric value within safe integer range.
     *
     * Valid range: `Number.MIN_SAFE_INTEGER` to `Number.MAX_SAFE_INTEGER`
     *
     * Invalid values:
     *
     * - Infinity or -Infinity
     * - NaN
     * - Negative zero (-0)
     * - Denormalized numbers
     *
     * Use `undefined` for an empty cell.
     */
    value: number | undefined;
    /**
     * Optional formatting information for displaying the number.
     *
     * @example Applying display formatting to a number
     * ```ts
     * import type { NumberCellMetadata } from '@canva/intents/data';
     *
     * const currencyFormatting: NumberCellMetadata = { formatting: '[$USD]#,##0.00' };
     * const percentageFormatting: NumberCellMetadata = { formatting: '0.00%' };
     * ```
     */
    metadata?: NumberCellMetadata;
};

/** @public */
declare type OnContextChange = (context: SettingsUiContext) => void;

/**
 * @public
 * {@link GetDataTableError} indicating the data source reference is no longer valid.
 * This will trigger a re-selection flow for the user.
 */
declare type OutdatedSourceRefError = {
    /**
     * The data source reference is no longer valid.
     *
     * Return this error when the DataSourceRef cannot be used to retrieve data,
     * for example:
     *
     * - The referenced dataset has been deleted
     * - Access permissions have changed
     * - The structure of the data has fundamentally changed
     *
     * This will trigger a re-selection flow, allowing the user to choose a new
     * data source.
     */
    status: 'outdated_source_ref';
};

/**
 * @public
 * {@link InvocationContext} indicating an error occurred because the previously selected data source reference is no longer valid.
 * Triggered when getDataTable returned 'outdated_source_ref' during data refresh.
 * UI should guide the user to reselect or reconfigure their data.
 */
declare type OutdatedSourceRefInvocationContext = {
    /**
     * Previously selected data source reference is no longer valid.
     *
     * This occurs when `getDataTable` returned 'outdated_source_ref' during a
     * refresh attempt. Your UI should guide the user to select a new data source
     * or update their selection.
     *
     * The outdated reference is provided to help you suggest an appropriate replacement.
     */
    reason: 'outdated_source_ref';
    /**
     * The outdated data source reference that caused the error during refresh.
     */
    dataSourceRef?: DataSourceRef;
};

/**
 * @public
 * Exported file ready for publishing.
 */
declare type OutputFile = ImageOutputFile | VideoOutputFile | DocumentOutputFile;

/**
 * @public
 * Production-ready exported files for a specific media slot.
 *
 * These are the final files that should be uploaded to your platform.
 */
declare type OutputMedia = {
    /**
     * ID of the media slot these files belong to.
     *
     * Matches a media slot ID from your output type definition.
     */
    mediaSlotId: string;
    /**
     * Array of exported files for this media slot.
     *
     * Files match the requirements specified in your media slot configuration.
     */
    files: OutputFile[];
};

/**
 * @public
 * Metadata about a specific page in the exported content.
 */
declare type OutputPageMetadata = {
    /**
     * The unique identifier for the page.
     */
    pageId: string | undefined;
    /**
     * The position of the page within the design, starting from 1 for the first page.
     */
    pageNumber: number;
};

/**
 * @public
 * Configuration for an output type.
 *
 * Defines a specific publishing format your platform supports,
 * including what media is required and accepted file types.
 *
 * @example Defining an Instagram post output type
 * ```ts
 * const instagramPost: OutputType = {
 *   id: 'instagram_post',
 *   displayName: 'Instagram Post',
 *   mediaSlots: [
 *     {
 *       id: 'main_image',
 *       displayName: 'Post Image',
 *       fileCount: { min: 1, max: 10 },
 *       accepts: {
 *         image: {
 *           format: 'jpg',
 *           aspectRatio: { min: 0.8, max: 1.91 },
 *         }
 *       }
 *     }
 *   ]
 * };
 * ```
 */
declare type OutputType = {
    /**
     * Unique identifier for this output type.
     *
     * Use descriptive IDs like `"instagram_post"` or `"youtube_video"`.
     */
    id: string;
    /**
     * User-facing name for this output type.
     *
     * This is displayed to users when selecting where to publish.
     * Examples: `"Instagram Post"`, `"YouTube Video"`, `"Twitter Post"`.
     */
    displayName: string;
    /**
     * Array of media slots defining what content is needed.
     *
     * Each slot represents a piece of media required for publishing,
     * such as a main image, thumbnail, or video.
     */
    mediaSlots: MediaSlot[];

};

/**
 * @public
 * Configuration for an output type as provided by apps in
 * {@link ContentPublisherIntent.getPublishConfiguration}.
 *
 * This is the authored shape of an output type. It omits the
 * {@link MediaSlot.selection} field which is populated by Canva
 * when returning {@link OutputType} in Settings UI contexts.
 *
 * @example Defining output type configuration for a social media platform
 * ```ts
 * const outputType: OutputTypeConfiguration = {
 *   id: 'instagram_post',
 *   displayName: 'Instagram Post',
 *   mediaSlots: [
 *     {
 *       id: 'main_image',
 *       displayName: 'Post Image',
 *       fileCount: { min: 1, max: 10 },
 *       accepts: {
 *         image: { format: 'jpg', aspectRatio: { min: 0.8, max: 1.91 } }
 *       }
 *     }
 *   ]
 * };
 * ```
 */
declare type OutputTypeConfiguration = {
    /**
     * Unique identifier for this output type.
     *
     * Use descriptive IDs like `"instagram_post"` or `"youtube_video"`.
     */
    id: string;
    /**
     * User-facing name for this output type.
     *
     * This is displayed to users when selecting where to publish.
     * Examples: `"Instagram Post"`, `"YouTube Video"`, `"Twitter Post"`.
     */
    displayName: string;
    /**
     * Array of media slots defining what content is needed.
     *
     * Each slot represents a piece of media required for publishing,
     * such as a main image, thumbnail, or video.
     * The {@link MediaSlot.selection} field is omitted here because apps
     * do not provide selection data when defining output types.
     */
    mediaSlots: Omit<MediaSlot, 'selection'>[];

};

/**
 * @public
 * Action to be taken after publishing completes successfully.
 */
declare type PostPublishAction = PostPublishActionRedirect;

/**
 * @public
 * Redirect action to navigate the user to a URL after publishing.
 *
 * @example Redirecting to content editor
 * ```ts
 * const postPublishAction: PostPublishActionRedirect = {
 *   type: 'redirect',
 *   url: 'https://example.com/posts/12345/edit'
 * };
 * ```
 */
declare type PostPublishActionRedirect = {
    type: 'redirect';
    /**
     * The URL to redirect the user to after publishing.
     */
    url: string;
};

/**
 * @public
 *
 * Prepares a {@link ContentPublisherIntent|Content Publisher Intent}.
 *
 * @example
 * ```tsx
 * import { prepareContentPublisher } from "@canva/intents/content";
 *
 * prepareContentPublisher({
 *  getPublishConfiguration: async (params) => {
 *    // Implement the logic to get the publish configuration
 *  },
 *  renderSettingsUi: (params) => {
 *    // Implement the UI for settings view
 *  },
 *  renderPreviewUi: (params) => {
 *    // Implement the UI for preview view
 *  },
 *  publishContent: async (params) => {
 *    // Implement the logic to publish the content
 *  },
 * });
 * ```
 */
declare const prepareContentPublisher: (implementation: ContentPublisherIntent) => void;

/**
 * @public
 *
 * Prepares a {@link DataConnectorIntent|DataConnector Intent}.
 *
 * @example
 * ```tsx
 * import { prepareDataConnector } from "@canva/intents/data";
 *
 * prepareDataConnector({
 *  getDataTable: async (params) => {
 *    // Implement the logic to fetch the data table
 *  },
 *  renderSelectionUi: (params) => {
 *    // Implement the UI for the data table selection
 *  },
 * });
 * ```
 */
declare const prepareDataConnector: (implementation: DataConnectorIntent) => void;

/**
 * @public
 *
 * Prepares a {@link DesignEditorIntent|DesignEditor Intent}.
 *
 * @example
 * ```tsx
 * import { prepareDesignEditor } from '@canva/intents/design';
 *
 * prepareDesignEditor({
 *  render: async () => {
 *    // TODO: Implement the logic to render your app's UI
 *  },
 * });
 * ```
 */
declare const prepareDesignEditor: (implementation: DesignEditorIntent) => void;

/**
 * @public
 * Preview item for an image or video.
 *
 * Check the `kind` and `status` properties to determine the type and state.
 */
declare type Preview = ImagePreview | VideoPreview | DocumentPreview | EmailPreview;

/**
 * @public
 * Type of preview media.
 */
declare type PreviewKind = 'image' | 'video' | 'document' | 'email';

/**
 * @public
 * Preview media for a specific media slot.
 *
 * Contains preview URLs and metadata for images or videos in the design.
 */
declare type PreviewMedia = {
    /**
     * ID of the media slot this preview belongs to.
     *
     * Matches a media slot ID from your output type definition.
     */
    mediaSlotId: string;
    /**
     * Array of preview items for this media slot.
     *
     * May contain multiple previews if the media slot accepts multiple files.
     */
    previews: Preview[];
};

/**
 * @public
 * State of a preview item.
 */
declare type PreviewStatus = 'loading' | 'thumbnail' | 'upgrading' | 'ready' | 'error';

/**
 * @public
 * Successful response from publishing a content.
 *
 * @example Basic successful publish
 * ```ts
 * return {
 *   status: 'completed',
 *   externalId: 'post_12345',
 *   externalUrl: 'https://example.com/posts/12345'
 * };
 * ```
 *
 * @example Successful publish with redirect
 * ```ts
 * return {
 *   status: 'completed',
 *   externalId: 'video_67890',
 *   externalUrl: 'https://example.com/videos/67890',
 *   postPublishAction: {
 *     type: 'redirect',
 *     url: 'https://example.com/videos/67890/edit'
 *   }
 * };
 * ```
 */
declare type PublishContentCompleted = {
    status: 'completed';
    /**
     * Unique identifier returned from your external platform. You can use this for:
     *
     * - Tracking published content
     * - Fetching insights data for the published content
     * - Linking back to the content in future operations
     */
    externalId?: string;
    /**
     * Direct URL to the published content on your platform.
     *
     * Users can visit this URL to view their published content.
     * This may be displayed to users or used for sharing.
     */
    externalUrl?: string;
    /**
     * Optional action to perform after publishing completes.
     *
     * Currently supports redirecting users to a specific URL after publishing.
     */
    postPublishAction?: PostPublishAction;
};

/**
 * @public
 * Error response from publishing a content.
 *
 * Return the appropriate error type based on the failure:
 *
 * - `"remote_request_failed"`: Network or API errors with your platform
 * - `"app_error"`: Custom application errors with optional message
 */
declare type PublishContentError = RemoteRequestFailedError_2 | AppError_2;

/**
 * @public
 * Parameters required for publishing the content.
 * Contains all the information needed to send the content to your external platform.
 */
declare type PublishContentRequest = {
    /**
     * Platform-specific settings reference containing user configurations.
     *
     * This is the same reference you saved via `updatePublishSettings` in the settings UI.
     * Parse this string to retrieve the user's publish settings (e.g., captions, tags, privacy).
     *
     * Maximum size: 32KB
     */
    publishRef?: string;
    /**
     * The output type selected by the user for this publish operation.
     *
     * This matches one of the output types you provided in `getPublishConfiguration`.
     */
    outputType: OutputTypeConfiguration;
    /**
     * Production-ready exported files matching the requirements from your output type.
     *
     * These files are ready to upload to your platform and match the format, size,
     * and aspect ratio requirements specified in your media slots.
     */
    outputMedia: OutputMedia[];
};

/**
 * @public
 * Response from a publish content operation.
 *
 * This can be either a successful completion or an error response.
 */
declare type PublishContentResponse = PublishContentCompleted | PublishContentError;

/** @public */
declare type PublishError = {
    appDefinedPayload?: string;
};

/**
 * @public
 * Signals that the publish error was cleared.
 */
declare type PublishErrorClearedSettingsUiContext = {
    reason: 'publish_error_cleared';
};

/**
 * @public
 * Provides information about an error that occurred in publishContent.
 */
declare type PublishErrorSettingsUiContext = {
    reason: 'publish_error';
    /**
     * The error that occurred. Undefined means no error occurred or the previous
     * error was cleared by Canva.
     */
    error: PublishError;
};

/**
 * @public
 * Supported file formats for publishing.
 */
declare type PublishFileFormat = 'png' | 'jpg' | 'mp4' | 'pdf_standard' | 'html_bundle' | 'html_standalone';

/**
 * @public
 * Initial payload provided from cache.
 */
declare type PublishPreviewUiInvocationContext = {
    /**
     * Initial preview data and context provided when the preview UI is rendered.
     */
    reason: 'publish';
    /**
     * Initial preview media to display
     * This will only be used for scheduling and not caching
     */
    previewMedia?: PreviewMedia[];
    /** Information about the current output type being previewed */
    outputType?: OutputType;
    /** Current publish reference, if available */
    publishRef?: string;
};

/**
 * @public
 * Validation state indicating whether publish settings are complete and valid.
 */
declare type PublishRefValidityState = 'valid' | 'invalid_missing_required_fields' | 'invalid_authentication_required';

/**
 * @public
 * Configuration for publish settings.
 *
 * Contains the user's settings and their validation state. Use this to
 * control whether the publish button is enabled.
 */
declare type PublishSettings = {
    /**
     * Serialized platform-specific settings for publishing.
     *
     * Store all information your app needs to publish the content in this string.
     * This might include:
     *
     * - Captions or descriptions
     * - Tags or hashtags
     * - Privacy settings
     * - Publishing destination (account, page, etc.)
     * - Scheduling information
     *
     * This reference will be provided to your `publishContent` method when publishing.
     *
     * Maximum size: 32KB
     *
     * @example Serializing settings
     * ```ts
     * const settings = {
     *   caption: 'Check out my design!',
     *   tags: ['design', 'creative'],
     *   privacy: 'public'
     * };
     * const publishRef = JSON.stringify(settings);
     * ```
     */
    publishRef?: string;
    /**
     * Validation state of the publish settings.
     *
     * Controls whether the publish button is enabled:
     *
     * - `"valid"`: Settings are complete and valid, publish button is enabled
     * - `"invalid_missing_required_fields"`: Required settings are missing, publish button is disabled
     * - `"invalid_authentication_required"`: User must authenticate before publishing can proceed
     */
    validityState: PublishRefValidityState;
};

/**
 * @public
 * Provides information about the current state of the settings UI to help
 * you adapt the interface based on the selected output type.
 */
declare type PublishSettingsSettingsUiContext = {
    reason: 'publish_settings';
    /**
     * The currently selected output type.
     *
     * Use this to customize your settings UI based on the requirements
     * of different output types.
     */
    outputType: OutputType;
};

/**
 * @public
 * Initial payload provided from cache.
 */
declare type PublishSettingsUiInvocationContext = {
    /**
     * Initial settings and context provided when the settings UI is rendered.
     */
    reason: 'publish';
    /** Current publish reference to populate the UI, if any exist */
    publishRef?: string;
    /** Information about the current output type being configured */
    outputType?: OutputType;
};

/**
 * @public
 * {@link GetDataTableError} indicating failure to fetch data from the external source.
 * Typically due to network issues or API failures.
 */
declare type RemoteRequestFailedError = {
    /**
     * Failed to fetch data from the external source.
     *
     * Return this error for network issues, API failures, or other
     * connectivity problems that prevent data retrieval.
     */
    status: 'remote_request_failed';
};

/**
 * @public
 * {@link PublishContentError} indicating failure of the remote request to the external platform.
 *
 * Return this error for:
 *
 * - Network connectivity issues
 * - API endpoint failures
 * - HTTP errors from your platform
 * - Timeout errors
 *
 * @example Handling network errors
 * ```ts
 * try {
 *   await uploadToExternalPlatform(file);
 * } catch (error) {
 *   return { status: 'remote_request_failed' };
 * }
 * ```
 */
declare type RemoteRequestFailedError_2 = {
    status: 'remote_request_failed';
};

/**
 * @public
 * Initial payload provided when the preview UI is rendered.
 * Contains the preview data and settings needed to initialize the preview interface.
 */
declare type RenderPreviewUiInvocationContext = PublishPreviewUiInvocationContext;

/**
 * @public
 * Configuration required for rendering the preview UI.
 *
 * Provides callbacks for managing preview media and responding to preview updates.
 */
declare type RenderPreviewUiRequest = {
    /**
     * @public
     * The initial preview data and context provided when the preview UI is rendered.
     *
     * Contains the initial preview media, output type information, and any existing
     * publish settings needed to properly display the preview interface.
     */
    invocationContext: RenderPreviewUiInvocationContext;
    /**
     * Callback to upgrade thumbnail previews to full media.
     *
     * Call this function when you need full video or multi-page document previews
     * instead of lightweight thumbnails. This helps optimize performance by deferring
     * full media loading until needed.
     *
     * Upgrades may complete asynchronously; listen to `registerOnPreviewChange` for updates
     * to receive the upgraded previews.
     *
     * @param previewIds - Array of preview IDs to upgrade from thumbnail to full media
     *
     * @example Upgrading previews on user interaction
     * ```ts
     * // When user clicks on a thumbnail, upgrade to full preview
     * if (preview.status === 'thumbnail') {
     *   requestPreviewUpgrade([preview.id]);
     * }
     * ```
     */
    requestPreviewUpgrade: (previewIds: string[]) => void;
    /**
     * Registers a callback to be invoked when preview data changes.
     *
     * This callback is triggered when:
     *
     * - The design content changes
     * - The output type changes
     * - Preview media is upgraded from thumbnail to full video
     * - Export settings are modified
     *
     * Use this to update your preview UI in real-time as users modify their design.
     *
     * @param callback - The callback invoked when preview data is updated
     * @returns A disposer function that cleans up the registered callback
     *
     * @example Handling preview updates
     * ```ts
     * const disposer = registerOnPreviewChange(({ previewMedia, outputType, publishRef }) => {
     *   // Update your preview UI with the new preview media
     *   previewMedia.forEach((media) => {
     *     media.previews.forEach((preview) => {
     *       if (preview.status === 'ready') {
     *         displayPreview(preview);
     *       }
     *     });
     *   });
     * });
     *
     * // Clean up when preview UI is unmounted
     * onUnmount(() => disposer());
     * ```
     */
    registerOnPreviewChange: (callback: (opts: {
        previewMedia: PreviewMedia[];
        /** The output type that the preview data is for */
        outputType: OutputType;
        /** The current publish settings reference, if available */
        publishRef?: string;
    }) => void) => Disposer;
};

/**
 * @public
 * Parameters for rendering the data selection UI.
 */
declare type RenderSelectionUiRequest = {
    /**
     * Context information about why the data selection UI is being launched.
     *
     * Use this to adapt your UI for different scenarios:
     *
     * - 'data_selection': Initial data selection or editing existing data
     * - 'outdated_source_ref': Previous reference is no longer valid, guide user to reselect
     * - 'app_error': Custom error occurred, show error message and recovery options
     *
     * When `dataSourceRef` is provided, pre-populate your UI with this selection.
     */
    invocationContext: InvocationContext;
    /**
     * Maximum allowed rows and columns for the imported data.
     *
     * Your UI should inform users of these constraints and prevent or warn about
     * selections that would exceed them. This helps users understand why certain
     * data sets might not be available for selection.
     */
    limit: DataTableLimit;
    /**
     * Callback to preview selected data before finalizing import.
     *
     * Call this function when the user selects data to:
     *
     * 1. Show a preview of the selected data to the user
     * 2. Validate that the selection meets system requirements
     *
     * Calling this function will trigger your `getDataTable` implementation.
     * Wait for the promise to resolve to determine if the selection is valid.
     *
     * @param dataSourceRef - Reference object identifying the selected data
     * @returns Promise resolving to success or an error result
     * @throws Will throw CanvaError('bad_request') if
     *  1. {@link DataSourceRef.source} exceeds 5kb.
     *  2. {@link DataSourceRef.title} exceeds 255 characters.
     *  3. {@link GetDataTableCompleted.dataTable} exceeds {@link DataTableLimit} or contains invalid data.
     */
    updateDataRef: (dataSourceRef: DataSourceRef) => Promise<UpdateDataRefResponse>;
};

/**
 * @public
 * Initial payload provided when the publish settings UI is rendered.
 * Contains the current settings state needed to initialize the settings interface.
 */
declare type RenderSettingsUiInvocationContext = PublishSettingsUiInvocationContext;

/**
 * @public
 * Configuration for the publish settings UI.
 *
 * This type provides the necessary callbacks and configuration for rendering
 * a custom publish settings interface where users configure platform-specific options.
 */
declare type RenderSettingsUiRequest = {
    /**
     * @public
     * The initial settings and context provided when the settings UI is rendered.
     *
     * Contains any previously saved publish settings and information about the current output type being configured.
     * Use this to restore the UI to its previous state or initialise it with appropriate defaults.
     */
    invocationContext: RenderSettingsUiInvocationContext;
    /**
     * Callback to save and validate the user's publish settings.
     *
     * Call this function whenever the user modifies their settings to:
     *
     * - Save the settings for later use in `publishContent`
     * - Validate that required fields are filled
     * - Enable or disable the publish button based on validity
     *
     * Store all necessary publishing information in the `publishRef` string.
     * This will be provided to your `publishContent` method when the user publishes.
     *
     * @param settings - The new publish settings to save
     * @returns A promise that resolves when the settings are successfully saved
     * @throws Will throw `CanvaError('bad_request')` if {@link PublishSettings.publishRef} exceeds 32KB.
     *
     * @example Updating settings as user types
     * ```ts
     * // As user fills in form fields, update settings
     * function handleCaptionChange(caption: string) {
     *   const settings = { caption, tags: currentTags };
     *   const publishRef = JSON.stringify(settings);
     *
     *   updatePublishSettings({
     *     publishRef,
     *     validityState: caption ? 'valid' : 'invalid_missing_required_fields'
     *   });
     * }
     * ```
     */
    updatePublishSettings: (publishSettings: PublishSettings) => Promise<UpdatePublishSettingsResponse>;

    /**
     * Registers a callback to be invoked when the settings UI context changes.
     *
     * This callback is triggered when:
     * - the user changes the output type in the publish flow.
     * - an error occurs in the publish flow.
     *
     * Use this to respond to Canva changes and update your settings UI accordingly.
     *
     * @param opts - The options for registering a callback.
     * @returns A disposer function that cleans up the registered callback.
     *
     * @example Adapting UI for different output types
     * ```ts
     * registerOnContextChange({
     *   onContextChange: (ctx) => {
     *     if (ctx.reason === 'publish_settings') {
     *       if (ctx.outputType.id === 'instagram_post') {
     *         showHashtagField();
     *       }
     *     }
     *     if (ctx.reason === 'publish_error') {
     *       setError(ctx.error);
     *     }
     *   }
     * });
     * ```
     */
    registerOnContextChange: (opts: {
        onContextChange: OnContextChange;
    }) => Disposer;

};

/**
 * @public
 * Metadata specific to design content represented by a media selection.
 */
declare interface SelectionDesignMetadata {
    type: 'design';
    /**
     * A signed JWT token containing the design id
     */
    designToken: string;
    /**
     * The user given title of the design
     */
    title: string | undefined;
}

/**
 * @public
 * Metadata about the source content represented by a media selection.
 */
declare type SelectionMetadata = SelectionDesignMetadata;

/**
 * @public
 * Context information for the publish settings UI.
 */
declare type SettingsUiContext = PublishSettingsSettingsUiContext | PublishErrorSettingsUiContext | PublishErrorClearedSettingsUiContext;

/**
 * @public
 * Base interface for all preview types that have a fixed width and height.
 */
declare interface SizedPreview extends BasePreview {
    /**
     * Width of the preview in pixels.
     */
    widthPx: number;
    /**
     * Height of the preview in pixels.
     */
    heightPx: number;
}

/**
 * @public
 * Cell containing a text value.
 *
 * @example Creating a string cell
 * ```ts
 * import type { StringDataTableCell } from '@canva/intents/data';
 *
 * const nameCell: StringDataTableCell = {
 *   type: 'string',
 *   value: 'John Doe'
 * };
 *
 * const emptyStringCell: StringDataTableCell = {
 *   type: 'string',
 *   value: undefined
 * };
 * ```
 */
declare type StringDataTableCell = {
    /**
     * Indicates this cell contains a string value.
     */
    type: 'string';
    /**
     * Text content of the cell.
     *
     * Maximum length: 10,000 characters
     *
     * Use `undefined` for an empty cell.
     */
    value: string | undefined;
};

/**
 * @public
 * Successful result from the {@link RenderSelectionUiRequest.updateDataRef} callback.
 */
declare type UpdateDataRefCompleted = {
    /**
     * The data selection was successful and can be previewed.
     */
    status: 'completed';
};

/**
 * @public
 * Result returned from the {@link RenderSelectionUiRequest.updateDataRef} callback.
 * Indicates whether {@link DataSourceRef} update succeeded or failed.
 */
declare type UpdateDataRefResponse = UpdateDataRefCompleted | GetDataTableError;

/**
 * @public
 * Successful response from updating the publish settings.
 */
declare type UpdatePublishSettingsCompleted = {
    status: 'completed';
};

/**
 * @public
 * Response from updating the publish settings.
 */
declare type UpdatePublishSettingsResponse = UpdatePublishSettingsCompleted;

/**
 * @public
 * Numeric value range constraint.
 * Used to specify requirements for aspect ratios, durations, file counts, etc.
 */
declare type ValueRange = ExactValueRange | MinValueRange | MaxValueRange | MinMaxValueRange;

/**
 * @public
 * The MIME type of a video file that's supported by Canva's backend.
 *
 * @remarks
 * - GIFs are treated as videos, not images.
 * - `"application/json"` is only used for Lottie files.
 */
declare type VideoMimeType = 'video/avi' | 'video/x-msvideo' | 'image/gif' | 'video/x-m4v' | 'video/x-matroska' | 'video/quicktime' | 'video/mp4' | 'video/mpeg' | 'video/webm' | 'application/json';

/**
 * @public
 * Exported video file ready for publishing.
 */
declare interface VideoOutputFile extends BaseOutputFile {
    /**
     * Width of the video in pixels.
     */
    widthPx: number;
    /**
     * Height of the video in pixels.
     */
    heightPx: number;
}

/**
 * @public
 * Video preview in various states.
 *
 * Videos transition through states: `"loading"` → `"thumbnail"` → `"upgrading"` → `"ready"`.
 * Start with thumbnails for better performance, then upgrade to full video using `requestPreviewUpgrade`.
 */
declare type VideoPreview = VideoPreviewLoading | VideoPreviewThumbnail | VideoPreviewUpgrading | VideoPreviewReady | VideoPreviewError;

/**
 * @public
 * Video preview that failed to generate.
 *
 * Display an error state to the user.
 */
declare interface VideoPreviewError extends SizedPreview {
    kind: 'video';
    status: 'error';

    /**
     * The error message to display to the user.
     */
    message: string;
}

/**
 * @public
 * Video preview that is currently being generated.
 *
 * Display a loading state until the preview transitions to `"thumbnail"` or `"error"`.
 */
declare interface VideoPreviewLoading extends SizedPreview {
    kind: 'video';
    status: 'loading';
    /**
     * Video duration in milliseconds.
     */
    durationMs?: number;
}

/**
 * @public
 * Video preview with full video ready to play.
 *
 * Contains URLs for both the video and thumbnail.
 */
declare interface VideoPreviewReady extends SizedPreview {
    kind: 'video';
    status: 'ready';
    /**
     * Video format.
     */
    format: 'mp4';
    /**
     * URL to the full video.
     *
     * Use this URL in a video player.
     */
    url: string;
    /**
     * Format of the thumbnail image.
     */
    thumbnailFormat: 'png' | 'jpg';
    /**
     * URL to the thumbnail image.
     *
     * Can be used as a poster image for the video player.
     */
    thumbnailUrl: string;
    /**
     * Video duration in milliseconds.
     */
    durationMs?: number;
}

/**
 * @public
 * Video preview with lightweight thumbnail available.
 *
 * This is the initial state for video previews. Show the thumbnail image
 * and call `requestPreviewUpgrade` when the user needs the full video.
 */
declare interface VideoPreviewThumbnail extends SizedPreview {
    kind: 'video';
    status: 'thumbnail';
    /**
     * Format of the thumbnail image.
     */
    thumbnailFormat: 'png' | 'jpg';
    /**
     * URL to the thumbnail image.
     *
     * Display this lightweight image until full video is needed.
     */
    thumbnailUrl: string;
    /**
     * Video duration in milliseconds.
     */
    durationMs?: number;
}

/**
 * @public
 * Video preview that is being upgraded from thumbnail to full video.
 *
 * Display the thumbnail with a loading indicator until the video is ready.
 */
declare interface VideoPreviewUpgrading extends SizedPreview {
    kind: 'video';
    status: 'upgrading';
    /**
     * Format of the thumbnail image.
     */
    thumbnailFormat: 'png' | 'jpg';
    /**
     * URL to the thumbnail image.
     *
     * Continue showing the thumbnail while the full video loads.
     */
    thumbnailUrl: string;
    /**
     * Video duration in milliseconds.
     */
    durationMs?: number;
}

/**
 * @public
 * A unique identifier that points to a video asset in Canva's backend.
 */
declare type VideoRef = string & {
    __videoRef: never;
};

/**
 * @public
 * Video file requirements for a media slot.
 *
 * Specifies format, aspect ratio, duration, and size constraints for videos.
 *
 * @example Video requirements for YouTube
 * ```ts
 * const videoReq: VideoRequirement = {
 *   format: 'mp4',
 *   aspectRatio: { exact: 16/9 },
 *   durationMs: { min: 1000, max: 600000 },
 * };
 * ```
 */
declare interface VideoRequirement extends BaseFileRequirement {
    /**
     * Supported video format.
     */
    format: 'mp4';
    /**
     * Aspect ratio constraint (width / height).
     *
     * Examples:
     * - `{ exact: 16/9 }`: Widescreen
     * - `{ exact: 9/16 }`: Vertical/Story format
     */
    aspectRatio?: ValueRange;
    /**
     * Duration constraint in milliseconds.
     *
     * Examples:
     * - `{ max: 60000 }`: Maximum 60 seconds
     * - `{ min: 3000, max: 600000 }`: Between 3 seconds and 10 minutes
     */
    durationMs?: ValueRange;

}

/**
 * @public
 * Selection metadata for a video media item.
 */
declare interface VideoSelection extends BaseSelection {
    kind: 'video';
    /**
     * Duration of the selected video in milliseconds.
     */
    durationMs: number;
}

/**
 * @public
 * Options for uploading a video asset to the user's private media library.
 */
declare type VideoUploadOptions = {
    /**
     * The type of asset.
     */
    type: 'video';
    /**
     * A human-readable name for the video asset.
     *
     * @remarks
     * This name is displayed in the user's media library and helps users identify
     * and find the asset later. If not provided, Canva will generate a name based
     * on the asset's URL or a unique identifier.
     *
     * Requirements:
     * - Minimum length: 1 character (empty strings are not allowed)
     * - Maximum length: 255 characters
     */
    name?: string;
    /**
     * The ref of the original asset from which this new asset was derived.
     *
     * @remarks
     * For example, if an app applies an effect to a video, `parentRef` should contain the ref of the original video.
     */
    parentRef?: VideoRef;
    /**
     * The URL of the video file to upload.
     *
     * @remarks
     * Requirements:
     *
     * - Must use HTTPS
     * - Must return a `200` status code
     * - `Content-Type` must match the file's MIME type
     * - Must be publicly accessible (i.e. not a localhost URL)
     * - Must not redirect
     * - Must not contain an IP address
     * - Maximum length: 4096 characters
     * - Must not contain whitespace
     * - Must not contain these characters: `>`, `<`, `{`, `}`, `^`, backticks
     * - Maximum file size: 1000MB (1GB)
     */
    url: string;
    /**
     * The MIME type of the video file.
     */
    mimeType: VideoMimeType;
    /**
     * The URL of a thumbnail video to display while the video is queued for upload.
     *
     * @remarks
     * Requirements:
     *
     * - Must use HTTPS
     * - Must support [Cross-Origin Resource Sharing](https://www.canva.dev/docs/apps/cross-origin-resource-sharing/)
     * - Maximum length: 4096 characters
     * - The dimensions of the thumbnail video must match the video's aspect ratio to prevent the thumbnail from appearing squashed or stretched
     * - Must not be an AVI file. Although our APIs support uploading AVI videos, Canva can't preview them because of native support of browsers
     */
    thumbnailVideoUrl?: string;
    /**
     * The URL of a thumbnail image to use as a fallback if `thumbnailVideoUrl` isn't provided.
     * This can be an external URL or a data URL.
     *
     * @remarks
     * Requirements for external URLs:
     *
     * - Must use HTTPS
     * - Must support [Cross-Origin Resource Sharing](https://www.canva.dev/docs/apps/cross-origin-resource-sharing/)
     * - Must be a PNG, JPEG, or SVG file
     * - Maximum length: 4096 characters
     *
     * Requirements for data URLs:
     *
     * - Must include `;base64` for base64-encoded data
     * - Maximum size: 10MB (10 × 1024 × 1024 characters)
     * - The dimensions of the thumbnail must match the video's aspect ratio to prevent the thumbnail from appearing squashed or stretched
     */
    thumbnailImageUrl: string;
    /**
     * A disclosure identifying if the app generated this video using AI.
     *
     * @remarks
     * Helps users make informed decisions about the content they interact with.
     * See {@link AiDisclosure} for the full definition.
     *
     * **App Generated**
     *
     * 'app_generated' indicates when the app creates or significantly alters an asset using AI. Includes when
     * the app requests a third-party service to take similar action on a video using AI.
     *
     *  Required for the following cases (this list is not exhaustive):
     *  | Case                                                             | Reason                               |
     *  | --                                                               | --                                   |
     *  | AI generates a new video from scratch                            | Creates new creative content         |
     *  | AI changes the style of the video e.g. makes it cartoon          | Significantly alters the style       |
     *  | AI adds subtitles that rely on subjective interpretation         | Creates new creative content         |
     *  | AI expands a video by generating new content to fill the edges   | Creates new creative content         |
     *  | AI animates an image                                             | Creates new creative content         |
     *  | AI fixes defects e.g. blur in a video by generating details      | Creates new creative content         |
     *  | AI generates a talking head presenter                            | Creates new creative content         |
     *
     * **None**
     *
     * 'none' indicates when the app doesn't create or significantly alter an asset using AI, or as a part of
     * a request to third-party hosted content.
     *
     * Required for the following cases (this list is not exhaustive):
     *  | Case                                                     | Reason                                    |
     *  | --                                                       | --                                        |
     *  | Asset comes from an asset library                        | Didn't generate the asset itself          |
     *  | AI corrects red eyes                                     | A minor correction                        |
     *  | AI adjusts brightness and contrast on a video            | Doesn't change original meaning by itself |
     *  | AI creates a slow motion effect in a video               | Doesn't change original meaning by itself |
     *  | AI adds AI word-by-word transcribed subtitles to a video | Doesn't change original meaning by itself |
     */
    aiDisclosure: AiDisclosure;

} & AllOrNone<Dimensions>;

export { }
