import type { HtmlEncodedCssList } from '../html/encode';
export declare const elevationSurfaceSunkenBg: HtmlEncodedCssList;
export declare const elevationSurfaceBg: HtmlEncodedCssList;
export declare const elevationSurfaceRaisedBg: HtmlEncodedCssList;
export declare const elevationSurfaceFloatingBg: HtmlEncodedCssList;
export declare const elevationSurfaceRestingShadow: HtmlEncodedCssList;
export declare const elevationSurfaceRaisedShadow: HtmlEncodedCssList;
export declare const elevationSurfaceFloatingShadow: HtmlEncodedCssList;
export declare const elevationActionRaised: HtmlEncodedCssList;
export declare const elevationActionResting: HtmlEncodedCssList;
